In [1]:
import pandas as pd

In [2]:
df_hotels = pd.read_json("../../2. Datasets/beta/hotelbeds/hotels_us_total_api_1.json")

In [3]:
df_hotels.head()

,code,name,description,countryCode,stateCode,destinationCode,zoneCode,coordinates,categoryCode,categoryGroupCode,...,interestPoints,images,wildcards,web,lastUpdate,S2C,ranking,terminals,issues,license
0,6474,{'content': 'Hilton Chicago'},{'content': 'Our Hotel's Policies Have Changed...,US,IL,ORD,2,"{'longitude': -87.6244, 'latitude': 41.8725}",4EST,GRUPO4,...,"[{'facilityCode': 10, 'facilityGroupCode': 100...","[{'imageTypeCode': 'HAB', 'path': '00/006474/0...","[{'roomType': 'ROO.LK', 'roomCode': 'ROO', 'ch...",www3.hilton.com/en/hotels/illinois/hilton-chic...,2023-07-28,3*,47,NaN,NaN,NaN
1,6478,{'content': 'Four Points by Sheraton Los Angel...,{'content': 'This charming hotel is just a mil...,US,CA,LAX,9,"{'longitude': -118.3859708, 'latitude': 33.948...",3EST,GRUPO3,...,NaN,"[{'imageTypeCode': 'RES', 'path': '00/006478/0...",NaN,http://www.fourpointslax.com/la-airport-hotel,2023-07-28,3*,82,NaN,NaN,NaN
2,6480,{'content': 'Sheraton Universal Hotel'},"{'content': 'This upscale, landmark hotel enjo...",US,CA,LAX,21,"{'longitude': -118.35955291287974, 'latitude':...",3EST,GRUPO3,...,NaN,"[{'imageTypeCode': 'GEN', 'path': '00/006480/0...",NaN,NaN,2023-07-28,4*,119,NaN,NaN,NaN
3,6483,{'content': 'Westin Copley Place'},{'content': 'Experience one of Boston's most c...,US,MA,BOS,2,"{'longitude': -71.077539, 'latitude': 42.348577}",H4_5,GRUPO4,...,NaN,"[{'imageTypeCode': 'GEN', 'path': '00/006483/0...","[{'roomType': 'DBL.ST', 'roomCode': 'DBL', 'ch...",http://www.westincopleyplaceboston.com/,2023-07-28,3*,62,NaN,NaN,NaN
4,6487,{'content': 'Wyndham Garden New Orleans Airport'},{'content': 'Wyndham Garden New Orleans Airpor...,US,LA,MSY,8,"{'longitude': -90.1227, 'latitude': 30}",3EST,GRUPO3,...,NaN,"[{'imageTypeCode': 'RES', 'path': '00/006487/0...","[{'roomType': 'DBL.KG', 'roomCode': 'DBL', 'ch...",www.wyndhamhotels.com,2023-07-28,NaN,55,NaN,NaN,NaN