![Banner ETL](<../5. Sources/Images/banner_etl.gif>)
# <h2 align=center>**`ETL GOOGLE MAPS (REVIEW-ESTADOS)`**</h2>
Debido a que existen 51 carpetas (1 para cada estado de USA) con varios archivos .json cada una, se debe buscar la ruta de acceso en el ordenador donde se encuentran las carpetas y sus archivos. Luego, un ciclo 'for' alimentará una función con la ruta de cada carpeta y esta (la función) unirá cada archivo .json en un dataframe. Cada uno de estos dataframes se cruzará con los datos contenidos en el dataframe 'metada' dando como resultado solo información (reviews o reseñas) del rubro 'hotel'. Al final, se generará un solo dataframe con toda la información.

Importar las librerias necesarias

In [2]:
import pandas as pd
import numpy as np
import os

Importar el dataset 'metadata' para su posterior cruce con el dataframe de cada estado

In [8]:
#Dataframe 'metadata'
df_metadata = pd.read_csv('D:\\Aldemar\\cursos\\SoyHenry\\Cohorte DataPT02\\PF_DS\\Google Maps\\metadata-sitios\\df_metadata.csv')
df_metadata.head(2)

,Unnamed: 0,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url,category_hotel
0,175,Basecamp Guesthouse,"Basecamp Guesthouse, 49010 SE Middle Fork Rd, ...",0x54907fca2751e187:0x3d6ae31ac18da483,NaN,47.471332,-121.686928,['Hotel'],5.0,8,NaN,NaN,NaN,NaN,"['0x54907c35e89f333f:0x121a0cbfbbb39d3a', '0x5...",https://www.google.com/maps/place//data=!4m2!3...,Hotel
1,3611,Sugar River Loft,"Sugar River Loft, 929 W Exchange St, Brodhead,...",0x88062b28cb53ef6d:0x94df72568fddf391,NaN,42.619862,-89.377890,['Hotel'],4.7,8,NaN,NaN,NaN,NaN,"['0x88062b123701348f:0x5c12c6134b41325', '0x88...",https://www.google.com/maps/place//data=!4m2!3...,Hotel

Crear función que retorna un dataframe para cada estado

In [15]:
def union_arch_json(estado:str): #creación de la función

    df_estado = pd.DataFrame() #dataframe vacío (será el que contenga los datos de cada estado)

    directorio_estado = f'D:\\Aldemar\\cursos\\SoyHenry\\Cohorte DataPT02\\PF_DS\Google Maps\\reviews-estados\\reviews-estados\\{estado}' #ruta de los archivos .json para cada estado
    archivos_estado = os.listdir(directorio_estado) #lista de los archivos .json

    #crear dataframe con el contenido de los archivos .json
    for archivo in archivos_estado:
        df_archivo = pd.read_json(f'reviews-estados\\{estado}\\{archivo}', lines=True)
        df_archivo['estado'] = estado.replace('review-','') #creación de la columna 'estado'

        #concatenación de los datos en el dataframe
        if df_estado.shape[0] == 0:
            df_estado = df_archivo
        else:
            df_estado = pd.concat([df_estado, df_archivo])
        
    return df_estado #retorno del dataframe

Cruzar cada dataframe generado anteriormente con el dataframe metadata para posterior concatenación en un solo dataframe

In [16]:
directorio_estados = 'D:\\Aldemar\\cursos\\SoyHenry\\Cohorte DataPT02\\PF_DS\Google Maps\\reviews-estados\\reviews-estados' #ruta de las 51 carpetas (una para cada estado)
lista_estados = os.listdir(directorio_estados) #lista de las 51 carpetas 

df_estados = pd.DataFrame() #dataframe vacío (será el que contenga los datos del cruce)

#Alimentar la función, cruzar los dataframes 'metadata' y 'df_estado' y crear un solo dataframe que disponibilioce los datos
for estado in lista_estados:
    df_estado = union_arch_json(estado)
    df_estado = pd.merge(df_metadata, df_estado, on='gmap_id', how='inner')

    #unión de cada dataframe cruzado
    if df_estados.shape[0] == 0:
        df_estados = df_estado
    else:
        df_estados = pd.concat([df_estados, df_estado])

df_estados.to_csv("df_estados.csv") #exportar el dataframe en un archivo .csv

Visualización del dataframe final

In [17]:
df_estados

    Unnamed: 0                                   name_x  ...  resp   estado
0        71118  Holiday Inn Express & Suites Fultondale  ...  None  Alabama
1        71118  Holiday Inn Express & Suites Fultondale  ...  None  Alabama
2        71118  Holiday Inn Express & Suites Fultondale  ...  None  Alabama
3        71118  Holiday Inn Express & Suites Fultondale  ...  None  Alabama
4        71118  Holiday Inn Express & Suites Fultondale  ...  None  Alabama
..         ...                                      ...  ...   ...      ...
55       62314                             Lariat Motel  ...  None  Wyoming
56       62314                             Lariat Motel  ...  None  Wyoming
57       62314                             Lariat Motel  ...  None  Wyoming
58       62314                             Lariat Motel  ...  None  Wyoming
59       62314                             Lariat Motel  ...  None  Wyoming

[58216 rows x 25 columns]